// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application";

import ReviewsController from "./reviews_controller";
application.register("reviews", ReviewsController);
